fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = std::env::var("OUT_DIR").unwrap();

    // Skip cbindgen when cross-compiling (e.g. cargo-xwin sets RUSTFLAGS
    // that poison cbindgen's cargo metadata calls). The C header is
    // platform-independent so it only needs to be generated on the host.
    let host = std::env::var("HOST").unwrap_or_default();
    let target = std::env::var("TARGET").unwrap_or_default();
    if host != target {
        // Still need to produce the header file for the build to succeed.
        // Copy from the crate root if it exists (generated by a prior native build).
        let existing = format!("{crate_dir}/graphdblite.h");
        if std::path::Path::new(&existing).exists() {
            std::fs::copy(&existing, format!("{out_dir}/graphdblite.h")).ok();
        }
        return;
    }

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(cbindgen::Config::from_file(format!("{crate_dir}/cbindgen.toml")).unwrap())
        .generate()
        .expect("unable to generate C bindings")
        .write_to_file(format!("{out_dir}/graphdblite.h"));

    // Also write to the crate root for easy access.
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(cbindgen::Config::from_file(format!("{crate_dir}/cbindgen.toml")).unwrap())
        .generate()
        .expect("unable to generate C bindings")
        .write_to_file(format!("{crate_dir}/graphdblite.h"));
}
