/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** An embedded graph database with Cypher query support. */
export declare class Database {
  /** Open a database at the given file path. */
  constructor(path: string)
  /** Open a database with a custom busy timeout (milliseconds). */
  static openWithTimeout(path: string, busyTimeoutMs: number): Database
  /** Open an in-memory database (for testing). */
  static openMemory(): Database
  /** Execute a read-only Cypher query. Returns an array of objects. */
  query(cypher: string): Array<object>
  /** Execute a write Cypher query (CREATE, DELETE, SET, MERGE). Returns an array of objects. */
  execute(cypher: string): Array<object>
  /**
   * Begin a read-write transaction. Pair with `commit()` or `rollback()`.
   * On Node 22+ the returned object is also `Symbol.dispose`-friendly via
   * the `using` syntax (rolls back on scope exit).
   */
  beginWrite(): WriteTransaction
  /** Begin a read transaction. Pair with `commit()`. */
  beginRead(): ReadTransaction
  /**
   * Write a consistent single-file snapshot of this database to `path`.
   *
   * Uses SQLite's `VACUUM INTO`: produces a self-contained file (no
   * `-wal` / `-shm` sidecars), defragmented and compacted. Throws when a
   * transaction is active on this handle or when `path` already exists.
   */
  snapshotTo(path: string): void
  /** Close the database connection. */
  close(): void
}
/** A read-write transaction. Created via `Database.beginWrite()`. */
export declare class WriteTransaction {
  /** Execute a Cypher query within this transaction. */
  execute(cypher: string): Array<object>
  /** Execute a Cypher query within this transaction (alias for `execute`). */
  query(cypher: string): Array<object>
  /** Create a secondary index on (label, property) for faster lookups. */
  createIndex(label: string, property: string): void
  /** Drop a secondary index on (label, property). */
  dropIndex(label: string, property: string): void
  /**
   * Create a fulltext index on (label, property). Accelerates
   * CONTAINS / STARTS WITH / ENDS WITH via SQLite FTS5 (trigram, case-sensitive).
   */
  createFulltextIndex(label: string, property: string): void
  /**
   * Create a case-insensitive fulltext index on (label, property).
   * Uses SQLite FTS5 trigram tokenizer with case_sensitive=0, so
   * CONTAINS / STARTS WITH / ENDS WITH against this property is
   * case-insensitive.
   */
  createFulltextIndexCi(label: string, property: string): void
  /**
   * Create a word-tokenized fulltext index on (label, property).
   * Uses SQLite FTS5 `unicode61` tokenizer, intended for use with
   * the `fts.search` CALL procedure (bm25 ranking on word matches).
   * Does NOT accelerate `CONTAINS` / `STARTS WITH` / `ENDS WITH`.
   */
  createFulltextIndexWord(label: string, property: string): void
  /** Drop a fulltext index on (label, property). */
  dropFulltextIndex(label: string, property: string): void
  /** Commit the transaction. */
  commit(): void
  /** Rollback the transaction. */
  rollback(): void
}
/** A read-only transaction. Created via `Database.beginRead()`. */
export declare class ReadTransaction {
  /** Execute a read-only Cypher query within this transaction. */
  query(cypher: string): Array<object>
  /** Commit (release) the read transaction. */
  commit(): void
}
