from typing import Any

class GraphDBError(Exception): ...
class ParseError(GraphDBError): ...
class StorageError(GraphDBError): ...
class NodeNotFoundError(GraphDBError): ...

class Database:
    def __init__(self, path: str, busy_timeout_ms: int = 5000) -> None: ...
    @staticmethod
    def open_memory() -> Database: ...
    def query(self, cypher: str) -> list[dict[str, Any]]: ...
    def execute(self, cypher: str) -> list[dict[str, Any]]: ...
    def snapshot_to(self, path: str) -> None: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Database: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any | None,
    ) -> bool: ...
