from collections.abc import Mapping
from types import TracebackType
from typing import Any

# Result row alias — each row is a dict keyed by column name.
Row = dict[str, Any]
# Parameters dict — accepted by query/execute.
Params = Mapping[str, Any]

class GraphDBError(Exception): ...
class ParseError(GraphDBError): ...
class StorageError(GraphDBError): ...
class NodeNotFoundError(GraphDBError): ...

class Database:
    def __init__(self, path: str, busy_timeout_ms: int = 5000) -> None: ...
    @staticmethod
    def open_memory() -> Database: ...
    def query(self, cypher: str, params: Params | None = None) -> list[Row]: ...
    def execute(self, cypher: str, params: Params | None = None) -> list[Row]: ...
    def begin_write(self) -> WriteTransaction: ...
    def begin_read(self) -> ReadTransaction: ...
    def snapshot_to(self, path: str) -> None: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Database: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: TracebackType | None = None,
    ) -> bool: ...

class WriteTransaction:
    def execute(self, cypher: str, params: Params | None = None) -> list[Row]: ...
    def query(self, cypher: str, params: Params | None = None) -> list[Row]: ...
    def create_index(self, label: str, property: str) -> None: ...
    def drop_index(self, label: str, property: str) -> None: ...
    def create_composite_index(self, label: str, properties: list[str]) -> None: ...
    def drop_composite_index(self, label: str, properties: list[str]) -> None: ...
    def create_fulltext_index(self, label: str, property: str) -> None: ...
    def create_fulltext_index_ci(self, label: str, property: str) -> None: ...
    def create_fulltext_index_word(self, label: str, property: str) -> None: ...
    def create_fulltext_index_word_multi(
        self, label: str, properties: list[str]
    ) -> None: ...
    def drop_fulltext_index(self, label: str, property: str) -> None: ...
    def batch_create_nodes(
        self, label: str, nodes: list[dict[str, Any]]
    ) -> list[int]: ...
    def batch_create_edges(
        self,
        edge_type: str,
        edges: list[tuple[int, int] | tuple[int, int, dict[str, Any]]],
    ) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> WriteTransaction: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: TracebackType | None = None,
    ) -> bool: ...

class ReadTransaction:
    def query(self, cypher: str, params: Params | None = None) -> list[Row]: ...
    def commit(self) -> None: ...
    def __enter__(self) -> ReadTransaction: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: TracebackType | None = None,
    ) -> bool: ...
